# Generated by Django 6.0.3 on 2026-03-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_session', models.CharField(default='2023/2024', max_length=20)),
                ('current_semester', models.CharField(default='First', max_length=20)),
                ('admissions_open', models.BooleanField(default=True)),
                ('course_registration_open', models.BooleanField(default=True)),
                ('result_upload_open', models.BooleanField(default=False)),
            ],
        ),
    ]
